---
# Colecciones de Ansible requeridas
collections:
  - name: community.docker
    version: ">=3.4.0"

  - name: community.general
    version: ">=7.0.0"

  - name: ansible.posix
    version: ">=1.5.0"
# Roles de Ansible Galaxy (opcional)
# roles:
#   - name: geerlingguy.docker
#     version: "6.1.0"
