---
# Playbook principal para despliegue de infraestructura
- name: Deploy Docker Swarm, Traefik and Portainer
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Install required system packages
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - software-properties-common
          - python3-pip
          - python3-setuptools
          - git
        state: present
      when: ansible_os_family == "Debian"

  roles:
    - role: docker
      tags: ['docker']

    - role: docker_swarm
      tags: ['swarm']

    - role: traefik
      tags: ['traefik']

    - role: portainer
      tags: ['portainer']

  post_tasks:
    - name: Verify Docker is running
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true

    - name: Display deployment summary
      ansible.builtin.debug:
        msg:
          - "Deployment completed successfully!"
          - "Docker version: {{ docker_version | default('latest') }}"
          - "Portainer accessible at: https://{{ ansible_host }}:{{ portainer_port_ssl }}"
          - "Environment: {{ env }}"
