---
# Inventario para ambiente de Producción
# Este inventario se usa DESPUÉS del bootstrap
# Para el bootstrap inicial, usar hosts-bootstrap.yml
all:
  children:
    production_servers:
      hosts:
        elefante:
          # Provider: https://contabo.com/
          ansible_host: 154.38.181.36 # Ajustar según IP de producción
          ansible_user: efemaq
          ansible_ssh_private_key_file: ./provision/.ssh/id_ed25519
          ansible_python_interpreter: /usr/bin/python3
        # prod-server-02:
        #   ansible_host: 10.0.0.11
        #   ansible_user: efemaq
        #   ansible_ssh_private_key_file: ./provision/.ssh/id_ed25519
        #   ansible_python_interpreter: /usr/bin/python3
      vars:
        env: production
        docker_edition: ce
        docker_users:
          - efemaq
        portainer_version: latest
        portainer_port: 9000
        portainer_port_ssl: 9443
